# Omakase Ruby styling for Rails
inherit_from: ./.rubocop-rails-omakase.yml

AllCops:
  Exclude:
    - "bin/*"
    - "storage/**/*"
    - "app/views/**/*"  # No need to lint views

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'hash']

Style/StringLiterals:
  Enabled: false
