name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install && bundle show

      - name: Run Overcommit
        run: |
          bundle exec overcommit --sign
          bundle exec overcommit --sign pre-commit
          SKIP=AuthorName,AuthorEmail bundle exec overcommit --run

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.7-alpine
        env:
          POSTGRES_DB: support_ticket_system_test
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: "123123"
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://runner:123123@postgres:5432/support_ticket_system_test
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: support_ticket_system_test
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: "123123"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
