name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.7-alpine
        env:
          POSTGRES_DB: support_ticket_system_test
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: "123123"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U runner -d support_ticket_system_test"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 10

    env:
      RAILS_ENV: test
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: support_ticket_system_test
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: "123123"
      DB_POOL: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Debug Running Services
        run: docker ps -a  # ✅ Show running containers

      - name: Show PostgreSQL Logs (for debugging)
        run: docker logs $(docker ps -q --filter ancestor=postgres) || echo "No logs available"

      - name: Wait for PostgreSQL to become ready
        run: |
          for i in {1..20}; do
            pg_isready -h postgres -p 5432 -U runner && exit 0 || (echo "Waiting for PostgreSQL..." && sleep 3)
          done
          echo "PostgreSQL did not start in time" && exit 1

      - name: Set up database
        run: bundle exec rake db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec test/dummy/spec
