name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install && bundle show

      - name: Run Overcommit
        run: |
          bundle exec overcommit --sign
          bundle exec overcommit --sign pre-commit
          SKIP=AuthorName,AuthorEmail bundle exec overcommit --run

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.7-alpine
        env:
          POSTGRES_DB: support_ticket_system_test
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: "123123"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U runner -h 127.0.0.1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://runner:123123@127.0.0.1:5432/support_ticket_system_test
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      POSTGRES_DB: support_ticket_system_test
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: "123123"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up database
        run: RAILS_ENV=test bundle exec rake db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec test/dummy/spec
