image: ruby:3.4.1

services:
  - postgres:16.7-alpine

variables:
  RAILS_ENV: test
  RACK_ENV: test
  POSTGRES_DB: support_ticket_system_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "123123"

stages:
  - build
  - linter
  - test

build_job:
  stage: build
  script:
    - bundle install
  except:
    - main
    - tags
  tags:
    - develop

linter_job:
  stage: linter
  variables:
    RAILS_ENV: test
    NODE_ENV: test
  before_script:
    - ruby -v
    - bundler -v
    - bundle install && bundle show
  script:
    - bundle exec overcommit --sign
    - bundle exec overcommit --sign pre-commit
    - SKIP=AuthorName,AuthorEmail bundle exec overcommit --run
  except:
    - main
    - tags
  tags:
    - develop

test_job:
  stage: test
  script:
    - bundle install
    - RAILS_ENV=test bundle exec rake db:create db:schema:load
    - bundle exec rspec test/dummy/spec
  except:
    - main
    - tags
  tags:
    - develop
