name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    variables:
      RAILS_ENV: test
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Overcommit
        run: |
          bundle exec overcommit --sign
          bundle exec overcommit --sign pre-commit
          SKIP=AuthorName,AuthorEmail bundle exec overcommit --run

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.7-alpine
        env:
          RAILS_ENV: test
          RACK_ENV: test
          POSTGRES_DB: support_ticket_system_test
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: "123123"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U runner -d support_ticket_system_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Wait for PostgreSQL to become ready
        run: sleep 10

      - name: Install dependencies
        run: bundle install

      - name: Set up database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://runner:123123@localhost:5432/support_ticket_system_test
        run: RAILS_ENV=test bundle exec rake db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec test/dummy/spec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
